concurrency: 16
run:
  deadline: 10m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters-settings:
  godox:
    keywords:
      - FIXME

issues:
  max-same-issues: 0

linters:
  enable:
    - scopelint
    - govet
    - ineffassign
    - varcheck
    - unused
    - deadcode
    - bodyclose
    - structcheck
    - staticcheck
    - godox
    - rowserrcheck
    - prealloc
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - interfacer
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - scopelint
    - sloglint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    - wastedassign
    - whitespace
    - zerologlint

  disable-all: true
  fast: false
